"""Canonical filesystem paths for RoboFactory experiments.

Single source of truth for run artifacts, debug-output scratch, and the
manifest. Lives in robofactory (not openpi) because openpi outlives the
simulator and shouldn't accumulate experiment-tracking paths.

The bash mirror is robofactory/utils/paths.sh — keep them in sync.
"""
from __future__ import annotations

import datetime
from pathlib import Path

USER_HOME = Path("/iris/u/mikulrai")

# Canonical artifact root for new training/eval runs.
# Layout: RUN_ROOT/<model>/<dataset>/<task>/<run_id>/
RUN_ROOT = USER_HOME / "runs"

# Scratch root for debug-script output. Files older than 30 days are removed
# by the cron installed via install_debug_output_cron.sh — do not write
# anything here that needs to survive longer.
DEBUG_OUTPUT_ROOT = USER_HOME / "debug_output"

# Single-file manifest of all canonical runs (regenerated by `make manifest`).
MANIFEST_PATH = RUN_ROOT / "manifest.csv"


def debug_output_dir(script_path: str | Path, date: str | None = None) -> Path:
    """Default --output_dir for debug scripts.

    Returns ``DEBUG_OUTPUT_ROOT/<script-stem>_<YYYYMMDD>/`` so each run of a
    given script lands in its own dated bucket. Date defaults to today.
    """
    stem = Path(script_path).stem
    date_str = date or datetime.date.today().strftime("%Y%m%d")
    return DEBUG_OUTPUT_ROOT / f"{stem}_{date_str}"
